### ISSUE TITLE
gradle 报错

### ISSUE THREAD

**Issue by LeoLee0097** [Dsiner/DMusic#1]
Error:Execution failed for task ':commen:javaPreCompileDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - butterknife-7.0.1.jar (com.jakewharton:butterknife:7.0.1)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

**Comment by Dsiner** [comment]
打开项目时，弹出update gradle的对话框，你选了update？这样的话，解决方法：不要选择update gradle

**Comment by LeoLee0097** [comment]
是这样的，我的ButterKnife是：butterknife-zelezny这个版本的的，AS表示不适配，找不到指定的jar包呃呃

**Comment by LeoLee0097** [comment]
啊啊，问题解决了，不好意思，我把 gradle 升级到4.1会报错，虽然不知道为什么。我是按照您说的，重新导入并不升级，之后就能正常运行啦，十分感谢!
Aha, problem solved. I'm sorry, I upgraded 'gradle' to vision 4.1, but I don't know why, there is something wrong. I am in accordance with what you say, re-import without upgrading 'gradle' vision ,it works well, thank you ! LOL
