### ISSUE TITLE
The app keeps crashing. I'm unable to use it.

### ISSUE THREAD

**Issue by HarryHeights** [Dsiner/DMusic#4]
#### Describe the bug
I installed the apk file which I downloaded from the link in the readme document. After installation, I launched the app and it doesn't get past the start-up screen without crashing. I tried several times and it kept crashing.

#### Test Environment
Device; Redmi note 5 pro
OS; Android 8.1
Software version; Dmusic v1.0.3

#### Screen recording 

https://youtu.be/2Ir3czlddpk

#### Logcat

``` android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=1 contentView=com.d.music/0x7f0b008c vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

```

**Comment by Dsiner** [comment]
@HarryHeights 
Can you try reloading? this crash can't happen with other phones.
And, the logcat is not accurate and comprehensive.

**Comment by HarryHeights** [comment]
I uninstalled and installed the app again. I had same feedback. Plus the logcat was the same.

**Comment by Dsiner** [comment]
@HarryHeights 
I probably found the problem, Xiaomi mobile phone permissions adaptation problem. I will update the installation package in a few hours.

**Comment by Dsiner** [comment]
@HarryHeights 
Hi, the installation package has been updated.

**Comment by HarryHeights** [comment]
Alright lemme check it out.

**Comment by HarryHeights** [comment]
There should be a new apk file right?

**Comment by Dsiner** [comment]
@HarryHeights Same link, new apk

**Comment by HarryHeights** [comment]
Downloaded the new one. Still having same problem.

**Comment by Dsiner** [comment]
@HarryHeights 
1. Uninstall and then reinstall
2. Manually grant app permissions in the phone settings

After telling me the result, thank you

**Comment by HarryHeights** [comment]
Did as you said. Nothing's changed. I guess I'm cursed never to use this app. 😢😢😢

**Comment by Dsiner** [comment]
Hahaha(∩_∩)
I am very sorry about this, I will inform you if there is any news about the adaptation of this model phone.

**Comment by HarryHeights** [comment]
Alright. No qualms.

**Comment by Dsiner** [comment]
@HarryHeights 
Solved, the installation package has been updated.

**Comment by HarryHeights** [comment]
It works now

**Comment by Dsiner** [comment]
Ok
