### ISSUE TITLE
Add Privacy Policy and contributors guide document.

### ISSUE THREAD

**Issue by HarryHeights** [Dsiner/DMusic#5]
Hello, I'm Harry. I engage in creating documents for open source projects. It's part of my contribution in helping open source projects. One of the documents I engage in creating is a privacy policy. The privacy policy will give details about user information collection, use and security. I really don't know if you externally collect user information, but, if you don't, it's good to let end users know via a privacy policy.
Contributor's guidelines is also an important document that will help prospective collaborators contribute easily to your project.

I'll love to hear your thoughts on this.

**Comment by Dsiner** [comment]
The app does not collect user information.
Thanks for your suggestion. The privacy policy looks great, I don't think about it right now, but it would be great if you could help me add it.
