### ISSUE TITLE
(DMusic version 1.0.3) The application crashes when I try to open the application

### ISSUE THREAD

**Issue by XAMIR555** [Dsiner/DMusic#7]
#### Project Information 
* Repository-------------------:[Here](https://github.com/Dsiner/DMusic)
* Project Name---------------: [DMusic](https://github.com/Dsiner/Resouce/raw/master/app/DMusic/release/com.d.music_release.apk)
* Publisher--------------------:  [D siner Dsiner](https://github.com/Dsiner)
* My GitHub account--------:  [Here](https://github.com/XAMIR555)

#### Expected behavior

I was expecting the behavior that when I open the application, the application will open and I can easily access all of its options.

#### Actual behavior

The application crashes when I try to open the application

#### How to reproduce
* [Download ](https://github.com/Dsiner/Resouce/raw/master/app/DMusic/release/com.d.music_release.apk) the application 
* When the application is completely installed, try opening the application
* Note the Bug
* Browser/App version-: 1.0.3)
* Operating system----: 9.0.0

#### Recording Of The Bug
![20190508_151521.gif](https://ipfs.busy.org/ipfs/QmXzKFEH6RH5EvNHJb4h5ptjrzX8NaQNGdnTYzFe2SZsXo)

# Logcat

<pre><code>05-08 04:48:03.052 28844 28844 E AndroidRuntime: FATAL EXCEPTION: main
05-08 04:48:03.052 28844 28844 E AndroidRuntime: Process: com.d.music, PID: 28844
05-08 04:48:03.052 28844 28844 E AndroidRuntime: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=1 contentView=com.d.music/0x7f0b008c vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
05-08 04:48:03.052 28844 28844 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
05-08 04:48:03.052 28844 28844 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 04:48:03.052 28844 28844 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-08 04:48:03.052 28844 28844 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-08 04:48:03.052 28844 28844 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 04:48:03.052 28844 28844 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-08 04:48:03.052 28844 28844 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
05-08 04:48:09.470 29050 29050 E AndroidRuntime: FATAL EXCEPTION: main
05-08 04:48:09.470 29050 29050 E AndroidRuntime: Process: com.d.music, PID: 29050
05-08 04:48:09.470 29050 29050 E AndroidRuntime: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=1 contentView=com.d.music/0x7f0b008c vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
05-08 04:48:09.470 29050 29050 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
05-08 04:48:09.470 29050 29050 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 04:48:09.470 29050 29050 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-08 04:48:09.470 29050 29050 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-08 04:48:09.470 29050 29050 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 04:48:09.470 29050 29050 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-08 04:48:09.470 29050 29050 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
05-08 04:48:16.695 29168 29168 E AndroidRuntime: FATAL EXCEPTION: main
05-08 04:48:16.695 29168 29168 E AndroidRuntime: Process: com.d.music, PID: 29168
05-08 04:48:16.695 29168 29168 E AndroidRuntime: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=1 contentView=com.d.music/0x7f0b008c vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
05-08 04:48:16.695 29168 29168 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
05-08 04:48:16.695 29168 29168 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 04:48:16.695 29168 29168 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-08 04:48:16.695 29168 29168 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-08 04:48:16.695 29168 29168 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 04:48:16.695 29168 29168 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-08 04:48:16.695 29168 29168 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
05-08 04:48:24.626 29316 29316 E AndroidRuntime: FATAL EXCEPTION: main
05-08 04:48:24.626 29316 29316 E AndroidRuntime: Process: com.d.music, PID: 29316
05-08 04:48:24.626 29316 29316 E AndroidRuntime: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=1 contentView=com.d.music/0x7f0b008c vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
05-08 04:48:24.626 29316 29316 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
05-08 04:48:24.626 29316 29316 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 04:48:24.626 29316 29316 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-08 04:48:24.626 29316 29316 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-08 04:48:24.626 29316 29316 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 04:48:24.626 29316 29316 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-08 04:48:24.626 29316 29316 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
05-08 04:48:32.203 29423 29423 E AndroidRuntime: FATAL EXCEPTION: main
05-08 04:48:32.203 29423 29423 E AndroidRuntime: Process: com.d.music, PID: 29423
05-08 04:48:32.203 29423 29423 E AndroidRuntime: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=1 contentView=com.d.music/0x7f0b008c vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
05-08 04:48:32.203 29423 29423 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
05-08 04:48:32.203 29423 29423 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 04:48:32.203 29423 29423 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-08 04:48:32.203 29423 29423 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-08 04:48:32.203 29423 29423 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 04:48:32.203 29423 29423 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-08 04:48:32.203 29423 29423 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
05-08 05:02:22.738  6169  6169 E AndroidRuntime: FATAL EXCEPTION: main
05-08 05:02:22.738  6169  6169 E AndroidRuntime: Process: com.d.music, PID: 6169
05-08 05:02:22.738  6169  6169 E AndroidRuntime: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=1 contentView=com.d.music/0x7f0b008c vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
05-08 05:02:22.738  6169  6169 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1879)
05-08 05:02:22.738  6169  6169 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 05:02:22.738  6169  6169 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-08 05:02:22.738  6169  6169 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-08 05:02:22.738  6169  6169 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 05:02:22.738  6169  6169 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-08 05:02:22.738  6169  6169 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
</code></pre>

**Comment by Dsiner** [comment]
@XAMIR555 
Thanks for your advice.
I think this problem has been solved yesterday, there is no problem with my 9.0 phone.
Just re-download and reinstall then tell you the result. Thanks

**Comment by XAMIR555** [comment]
thanks for inform me  

that good issue has been solved now
